// Downloads the Google Fonts woff2 files this site uses into fonts/ and writes
// css/fonts.css with @font-face rules that point at the local copies.
//
// Why: fonts.googleapis.com + fonts.gstatic.com cost two extra DNS lookups and
// TLS handshakes before any Bengali text can render. On a rural 3G phone that
// is seconds of blank screen. Self-hosting removes both round trips and lets us
// preload the one body font each page actually needs.
//
// Run: node scripts/fetch-fonts.mjs   (only when adding a font or weight)
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const root = process.cwd();
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

// Every family/weight combination used anywhere on the site (see AGENTS.md > Fonts).
const CSS_URLS = [
  'https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@400;500;600;700&family=Noto+Serif+Bengali:wght@400;500;600;700&display=swap',
  'https://fonts.googleapis.com/css2?family=Noto+Sans+Bengali:wght@300;400;500;600;700&display=swap',
];

const subsetOf = (range) => range.startsWith('U+0951') ? 'bengali' : range.startsWith('U+0100') ? 'latin-ext' : 'latin';
const slug = (family) => family.toLowerCase().replace(/\s+/g, '-');

// url -> { family, subset, range, weights:Set }
const faces = new Map();
for (const cssUrl of CSS_URLS) {
  const res = await fetch(cssUrl, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${cssUrl}: HTTP ${res.status}`);
  const css = await res.text();
  for (const block of css.match(/@font-face\s*{[^}]*}/g) || []) {
    const family = block.match(/font-family:\s*'([^']+)'/)[1];
    const weight = block.match(/font-weight:\s*(\d+)/)[1];
    const url = block.match(/url\(([^)]+)\)/)[1];
    const range = block.match(/unicode-range:\s*([^;]+);/)[1].trim();
    const face = faces.get(url) || { family, subset: subsetOf(range), range, weights: new Set() };
    face.weights.add(Number(weight));
    faces.set(url, face);
  }
}

await mkdir(join(root, 'fonts'), { recursive: true });
const rules = [];
for (const [url, face] of faces) {
  const weights = [...face.weights].sort((a, b) => a - b);
  // Google serves variable fonts as one file for every weight; declare the range once.
  const weightLabel = weights.length > 1 ? `${weights[0]}-${weights.at(-1)}` : String(weights[0]);
  const file = `${slug(face.family)}-${weightLabel}-${face.subset}.woff2`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  await writeFile(join(root, 'fonts', file), Buffer.from(await res.arrayBuffer()));
  rules.push(`@font-face{font-family:'${face.family}';font-style:normal;font-weight:${weightLabel.replace('-', ' ')};font-display:swap;src:url(/fonts/${file}) format('woff2');unicode-range:${face.range}}`);
  console.log(`fonts/${file}`);
}

await writeFile(join(root, 'css', 'fonts.css'), `/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n${rules.join('\n')}\n`);
console.log(`Wrote css/fonts.css with ${rules.length} @font-face rules.`);
